export const HTTP_REQUEST_TEST_ID = {
  METHOD_SELECT: 'request-method-select',
  URL_INPUT: 'request-url-input',
  SEND_BUTTON: 'request-send-button',
  STOP_STREAM_BUTTON: 'request-stop-stream-button',
  RESPONSE_MODE_SELECT: 'request-response-mode-select',
  STREAM_FORMAT_SELECT: 'request-stream-format-select',
  RESPONSE_EDITOR: 'response-editor',
  REQUEST_OPTIONS_TAB: 'request-options-tab',
  REQUEST_OPTIONS_INPUT_KEY: 'request-options-input-key',
  REQUEST_OPTIONS_INPUT_VALUE: 'request-options-input-value',
  REQUEST_OPTIONS_TABLE_ROW_DELETE_BUTTON: 'request-options-table-row-delete-button',
  REQUEST_OPTIONS_TABLE_ROW_MASK_BUTTON: 'request-options-table-row-mask-button',
  REQUEST_OPTIONS_TABLE_ROW_VISIBILITY_BUTTON: 'request-options-table-row-visibility-button',
  REQUEST_BODY_EDITOR: 'request-body-editor',
};
