name: Bump version on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e

  bump:
    needs: e2e
    uses: MaxiGarcia13/gh-actions/.github/workflows/bump-version.yml@main
